echoTeleExpertise/echoTeleExpertise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('news/', views.news, name="news"),
    path('admin/', admin.site.urls),
    path('requests/', include('exams.url', namespace="exams")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('patients/', include('patients.urls', namespace="patients")),
    path('pages/', include('pages.urls', namespace="pages")),
    path('verify_email/<str:hash_code>/', views.activate_account, name="activate_account"),
    path('change_password/<str:hash_code>/', views.change_password, name="change_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

echoTeleExpertise/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('list_patients/', views.list_patients, name="list_patients"),
    path('telefiles/', views.telefiles, name="telefiles"),
    path('telefile/<int:request_id>', views.telefile, name="telefile"),
    path('telefile/share/<int:request_id>', views.share_request, name="share_request"),
    path('telefile/share_request/<int:request_id>', views.share_telefile, name="share_telefile"),
    path('telefile/send/<int:request_id>', views.send_rapport, name="send_rapport"),
    path('list_requests/', views.list_requests, name="list_requests"),
    path('list_doctors/', views.list_doctors, name="list_doctors"),
    path('doctor/<int:doctor_id>', views.doctor, name="doctor"),
    path('requests_history/', views.requests_history, name="requests_history"),
    path('opinions_history/', views.opinions_history, name="opinions_history")
]

echoTeleExpertise/patients/urls.py
from django.urls import path, include
from . import views

app_name = 'patients'

urlpatterns = [
    path('add/', views.add_patient, name="add_patient"),
    path('delete/<int:patient_id>/', views.delete_patient, name="delete_patient"),
    path('edit/<int:patient_id>/', views.edit_patient, name="edit_patient"),
    path('<int:patient_id>/', views.patient, name="patient")
]

echoTeleExpertise/patients/models.py
from django.db import models
from core.models import User
from datetime import datetime
from echoTeleExpertise.consts import GENDER_CHOICES

# Patients Model
class   Patient(models.Model):
    last_name = models.CharField('Nom', max_length=20)
    first_name = models.CharField('Prénom', max_length=30)
    cin = models.CharField('CIN', max_length=15)
    gender = models.CharField('Sexe', max_length=1, choices=GENDER_CHOICES)
    birthdate = models.DateField('Date de naissance')

    def     __str__(self):
        return (self.cin + ' | ' + self.last_name + ' ' + self.first_name)

# This Model is a relation many-to-many between Doctors & Patients
class   Relation(models.Model):
    patient_id = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor_id = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.CharField('Téléphone', max_length=10)
    join_date = models.DateTimeField('Date du premier contact', auto_now_add=True)

    def     __str__(self):
        return ('doctor ' + str(self.doctor_id) + ' | patient ' + str(self.patient_id))

echoTeleExpertise/patients/forms.py
from django.core.exceptions import ValidationError
from django import forms

class   PatientForm(forms.Form):
    gender = forms.CharField(label='Sexe', max_length=1)
    first_name = forms.CharField(label='Prénom', max_length=30)
    last_name = forms.CharField(label='Nom', max_length=20)
    phone = forms.CharField(label='Telephone', max_length=20)
    cin = forms.CharField(label='CIN', max_length=15)
    birthdate = forms.DateField(label='Date de naissance')

    # Clean the fields before puting them in the db:

    def     clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        # Test if the first_name contain numbers
        if not first_name.isalpha():
            raise ValidationError("Le prénom contient des nombres!")
        # Remove extra whitespaces
        first_name = ' '.join(first_name.split())
        # Capitalize the firstname
        first_name = first_name.capitalize()
        return first_name
    
    def     clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        # Test if the last_name contain numbers
        if not last_name.isalpha():
            raise ValidationError("Le nom contient des nombres!")
        # Remove extra whitespaces
        last_name = ' '.join(last_name.split())
        # Capitalize the lastname
        last_name = last_name.capitalize()
        return last_name

    def     clean_phone(self):
        phone = self.cleaned_data['phone']
        # Test if the first_name contain numbers
        chars = set('0123456789+-()')
        for c in phone:
            if not c in chars:
                raise ValidationError("Le numéro du téléphone doit contenir just '0123456789+-()' !")
        # Remove extra whitespaces
        phone = ' '.join(phone.split())
        return phone

    def     clean_cin(self):
        cin = self.cleaned_data['cin']
        # Test if the cin contain alphabetics and numbers
        if not cin.isalnum():
            raise ValidationError("Le C.I.N ne doit pas contenir des caractères spéciaux!")
        # Remove extra whitespaces
        cin = ' '.join(cin.split())
        # Uppercase the CIN
        cin = cin.upper()
        return cin

#############################################################

class   EditPatientForm(forms.Form):
    gender = forms.CharField(label='Sexe', max_length=1)
    first_name = forms.CharField(label='Prénom', max_length=30)
    last_name = forms.CharField(label='Nom', max_length=20)
    phone = forms.CharField(label='Telephone', max_length=20)
    birthdate = forms.DateField(label='Date de naissance')

    # Clean the fields before puting them in the db:

    def     clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        # Test if the first_name contain numbers
        if not first_name.isalpha():
            raise ValidationError("Le prénom contient des nombres!")
        # Remove extra whitespaces
        first_name = ' '.join(first_name.split())
        # Capitalize the firstname
        first_name = first_name.capitalize()
        return first_name
    
    def     clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        # Test if the last_name contain numbers
        if not last_name.isalpha():
            raise ValidationError("Le nom contient des nombres!")
        # Remove extra whitespaces
        last_name = ' '.join(last_name.split())
        # Capitalize the lastname
        last_name = last_name.capitalize()
        return last_name

    def     clean_phone(self):
        phone = self.cleaned_data['phone']
        # Test if the first_name contain numbers
        chars = set('0123456789+-()')
        for c in phone:
            if not c in chars:
                raise ValidationError("Le numéro du téléphone doit contenir just '0123456789+-()' !")
        # Remove extra whitespaces
        phone = ' '.join(phone.split())
        return phone

echoTeleExpertise/patients/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from mylib.notifications import get_summary_notifs
from .forms import PatientForm, EditPatientForm
from .models import Patient, Relation
from django.contrib import messages
from datetime import datetime

# Patient Detail
@login_required
def     patient(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    phone = Relation.objects.values_list('phone', flat=True).get(
        patient_id=patient_id,
        doctor_id=request.user
    )
    other_phones = Relation.objects.filter(
        patient_id=patient_id
    ).exclude(
        doctor_id=request.user
    ).order_by('-join_date').values_list('phone', flat=True)
    context = {
        'patient': patient,
        'main_phone': phone,
        'phones': other_phones,
        # Get the summary of notifications via the fonction
        'notifications': get_summary_notifs(request.user)
    }
    return render(request, 'patients/patient.html', context)


# Edit Patient
@login_required
def     edit_patient(request, patient_id):
    # Get the patient with th id = patient_id from the database
    patient = get_object_or_404(Patient, pk=patient_id)
    # Get the relation doctor/patient from the database
    try:
        relation = Relation.objects.get(
            patient_id=patient_id,
            doctor_id=request.user
        )
    except Relation.DoesNotExist:
        raise Http404("No Relation with this query.")
    # if the request is made with the method POST (the user submit some informations)
    if request.method == 'POST':
        form = EditPatientForm(request.POST)
        values = request.POST
        if form.is_valid():
            # Get infos
            last_name = form.cleaned_data['last_name']
            first_name = form.cleaned_data['first_name']
            phone = form.cleaned_data['phone']
            birthdate = request.POST['birthdate']
            gender = request.POST['gender']
            # Edit Infos
            patient.last_name = last_name
            patient.first_name = first_name
            patient.gender = gender
            patient.birthdate = birthdate
            relation.phone = phone
            # Save modifications in the database
            relation.save()
            patient.save()
            messages.success(request, 'La modification est enregister')
    else:
        form = EditPatientForm()
        values = {}
    context = {
        'form': form,
        'values': values,
        'patient': patient,
        'phone': relation.phone,
        # Get the summary of notifications via the fonction
        'notifications': get_summary_notifs(request.user)
    }
    return render(request, 'patients/edit_patient.html', context)


# Delete Patient
@login_required
def     delete_patient(request, patient_id):
    if request.method == 'POST':
        Relation.objects.filter(
            doctor_id=request.user,
            patient_id=patient_id
        ).delete()
        # If the patient doesn't have other relations with other doctors, we delete his account
        if not Relation.objects.filter(patient_id=patient_id).exists():
            Patient.objects.filter(pk=patient_id).delete()
        messages.success(request, 'Le patient est supprimer avec succès')
        return redirect('pages:list_patients')
    return HttpResponseNotAllowed('Not allowed to go to this page')


# Add New Patient
@login_required
def     add_patient(request):
    if request.method == 'POST':
        form = PatientForm(request.POST)
        values = request.POST
        if form.is_valid():
            # Get patient infos:
            last_name = form.cleaned_data['last_name']
            first_name = form.cleaned_data['first_name']
            cin = form.cleaned_data['cin']
            phone = form.cleaned_data['phone']
            gender = request.POST.get('gender', 'Homme')
            birthdate = request.POST.get('birthdate', datetime.now())
            # Check if the CIN is already used with this doctor:
            if Patient.objects.filter(
                pk__in=Relation.objects.filter(doctor_id=request.user).values_list('patient_id', flat=True),
                cin=cin
                ).exists():
                patient = Patient.objects.get(cin=cin)
                # Check if data entred by the user is like the one in the db
                if patient.first_name != first_name or patient.last_name != last_name or patient.gender != gender or patient.birthdate != birthdate:
                    messages.error(request, 'Faux informations! Un autre patient est déjà enregistrer avec ce C.I.N ou ce patient a donné une fause information!')
                    return redirect('patients:add_patient')
            else:
                patient = Patient(
                    last_name=last_name,
                    first_name=first_name,
                    cin=cin,
                    birthdate=birthdate,
                    gender=gender
                )
                # Save the new patient in the db
                patient.save()
            # Create the relation between the logged doctor and the new patient
            if Relation.objects.filter(doctor_id=request.user, patient_id=patient).exists():
                messages.warning(request, 'Vous avez déjà ce patient dans votre base de données!')
            else:
                relation = Relation(
                    doctor_id=request.user,
                    patient_id=patient,
                    phone=phone
                )
                # Save the relation
                relation.save()
                messages.success(request, 'Le nouveau patient est ajouté avec succès')
            return redirect('patients:add_patient')
    else:
        form = PatientForm()
        values = {}
    context = {
        'form': form,
        'values': values,
        # Get the summary of notifications via the fonction
        'notifications': get_summary_notifs(request.user)
    }
    return render(request, 'patients/add_patient.html', context)

echoTeleExpertise/templates/patients/edit_patient.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Modifier le profile du patient {% endblock %}

{% block body %}
<div class="row" style="width:100vw">
  <!-- Side Nav -->
  {% include 'pages/partials/_sideNav.html' %}

  <!-- Patient Informations -->
  <div class="col-9" style="margin: 2em 0;">

    <!-- Alert -->
    {% include 'partials/_alerts.html' %}

    <div class="container">
        <div class="row flex-lg-nowrap">
            <div class="col">
                <div class="col mb-3">
                    <form action="{% url 'patients:edit_patient' patient.pk %}" method='POST'>
                        {% csrf_token %}
                        <div class="card">
                            <div class="card-body">
                                <div class="e-profile">
                                    <div class="tab-content pt-3">
                                        <div class="tab-pane active">
                                                <div class="row">
                                                    <div class="col">
                                                        <!-- C.I.N -->
                                                        <div class="row">
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <label>C.I.N</label>
                                                                    <input class="form-control" type="text"
                                                                        value="{{ patient.cin }}" disabled>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <!-- Full Name -->
                                                        <div class="col px-0">
                                                            <!--- Last Name Validation Error --->
                                                            {% if form.last_name.errors %}
                                                                <div class="alert alert-danger" role="alert">
                                                                    <i class="fa fa-exclamation-circle fa-right-margin"></i>
                                                                    {{ form.last_name.errors | striptags }}
                                                                </div>
                                                            {% endif %}
                                                            <!--- First Name Validation Error --->
                                                            {% if form.first_name.errors %}
                                                            <div class="alert alert-danger" role="alert">
                                                                <i class="fa fa-exclamation-circle fa-right-margin"></i>
                                                                {{ form.first_name.errors | striptags }}
                                                            </div>
                                                            {% endif %}
                                                            <!--- Form --->
                                                            <div class="row">
                                                                <div class="col">
                                                                    <div class="form-group">
                                                                        <label>Nom</label>
                                                                        <input name="last_name" class="form-control" type="text"
                                                                            {% if values.last_name %}
                                                                                value="{{ values.last_name }}"
                                                                            {% else %}
                                                                                value="{{ patient.last_name }}"
                                                                            {% endif %}
                                                                            {% if form.last_name.errors %}
                                                                                style="border-color:red; color:red;"
                                                                            {% endif %}
                                                                        >
                                                                    </div>
                                                                </div>
                                                                <div class="col">
                                                                    <div class="form-group">
                                                                        <label>Prénom</label>
                                                                        <input name="first_name" class="form-control" type="text"
                                                                        {% if values.first_name %}
                                                                            value="{{ values.first_name }}"
                                                                        {% else %}
                                                                            value="{{ patient.first_name }}"
                                                                        {% endif %}
                                                                        {% if form.first_name.errors %}
                                                                            style="border-color:red; color:red;"
                                                                        {% endif %}
                                                                        >
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <!-- Sexe -->
                                                        <fieldset class="form-group">
                                                            <div class="row">
                                                            <legend class="col-form-label col-sm-2 pt-0">Sexe</legend>
                                                            <div class="col-sm-10">
                                                                <div class="form-check">
                                                                <input class="form-check-input" type="radio" name="gender" id="gridRadios1" value='M'
                                                                    {% if values.gender == 'M' %}
                                                                        checked
                                                                    {% else %}
                                                                        {% if not values.gender and patient.gender == 'M' %}
                                                                            checked
                                                                        {% endif %}
                                                                    {% endif %}
                                                                >
                                                                <label class="form-check-label" for="gridRadios1">Homme</label>
                                                                </div>
                                                                <div class="form-check">
                                                                <input class="form-check-input" type="radio" name="gender" id="gridRadios2" value='F'
                                                                    {% if values.gender == 'F' %}
                                                                        checked
                                                                    {% else %}
                                                                        {% if not values.gender and patient.gender == 'F' %}
                                                                            checked
                                                                        {% endif %}
                                                                    {% endif %}
                                                                >
                                                                <label class="form-check-label" for="gridRadios2">Femme</label>
                                                                </div>
                                                            </div>
                                                            </div>
                                                        </fieldset>

                                                        <!-- Birthday -->
                                                        <div class="form-group">
                                                            <label>Date de naissance</label>
                                                            <input type="date" name="birthdate" max="3000-12-31" min="1900-01-01" class="form-control"
                                                                {% if values.birthdate %}
                                                                    value="{{ values.birthdate }}"
                                                                {% else %}
                                                                    value="{{ patient.birthdate | date:'Y-m-d' }}"
                                                                {% endif %}
                                                            >
                                                        </div>

                                                        <!-- Phone -->
                                                        <div class="row">
                                                            <div class="col">
                                                                <div class="form-group">
                                                                    <!--- Phone Validation Error --->
                                                                    {% if form.phone.errors %}
                                                                    <div class="alert alert-danger" role="alert">
                                                                        <i class="fa fa-exclamation-circle fa-right-margin"></i>
                                                                        {{ form.phone.errors | striptags }}
                                                                    </div>
                                                                    {% endif %}
                                                                    <!--- Form --->
                                                                    <label>Téléphone</label>
                                                                    <input name="phone" class="form-control" type="text" 
                                                                        {% if values.phone %}
                                                                            value="{{ values.phone }}"
                                                                        {% else %}
                                                                            value="{{ phone }}"
                                                                        {% endif %}
                                                                        {% if form.phone.errors %}
                                                                            style="border-color:red; color:red;"
                                                                        {% endif %}
                                                                    >
                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Buttons -->
                        <div class="send-cancel">
                            <button type="submit" class="btn btn-success btn-lg btn-send">
                                Enregister
                            </button>
                            <a href="{% url 'patients:patient' patient.pk %}" class="btn btn-warning btn-lg btn-cancel">
                                Annuler
                            </a>
                        </div>
                    </form>
    
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

echoTeleExpertise/templates/patients/patient.html
{% extends 'base.html' %}
{% load myconvertions %}

{% block title %} {{ patient.last_name }} {{ patient.first_name }} {% endblock %}

{% block body %}
<div class="row" style="width:100vw">
  <!-- Side Nav -->
  {% include 'pages/partials/_sideNav.html' %}

  <!-- Doctor Informations -->
  <div class="col-9" style="margin: 2em 0;">
    
    <!-- Alert -->
    {% include 'partials/_alerts.html' %}
    
    <div class="container">
      <div class="card" style="margin: 0 1em">
        <div class="card-header" style="font-size: 1.3em;">
          Identité du patient:
        </div>
        <div class="card-body">
          <div class="card-body telefile-card-pd0">
            <table class="table telefile-card-mrg0">
              <tbody>
                <tr>
                  <th scope="row">C.I.N</th>
                  <td>{{ patient.cin }}</td>
                </tr>
                <tr>
                  <th scope="row">Nom</th>
                  <td>{{ patient.last_name }}</td>
                </tr>
                <tr>
                  <th scope="row">Prénom</th>
                  <td>{{ patient.first_name }}</td>
                </tr>
                <!-- List of phone numbers -->
                <tr>
                  <th scope="row">Téléphone</th>
                  <td>{{ main_phone }}</td>
                </tr>
                {% for phone in phones %}
                  <tr>
                    <th scope="row"></th>
                    <td>{{ phone }}</td>
                  </tr>
                {% endfor %}
                <tr>
                  <th scope="row">Sexe</th>
                  <td>{{ patient.get_gender_display }}</td>
                </tr>
                <tr>
                  <th scope="row">Date de naissance:</th>
                  <td>{{ patient.birthdate }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Buttons -->
      <div class="send-cancel">
        <a href="{% url 'exams:patient_request' patient.pk %}" class="btn btn-primary btn-lg btn-send">
          <i class="fa fa-plus fa-right-margin"></i>
          Demander un avis d'expertise pour ce patient
        </a>
        <a href="{% url 'patients:edit_patient' patient.pk %}" class="btn btn-info btn-lg btn-send">
          <i class="fa fa-pencil-alt fa-right-margin"></i>
          Modifier les informations de ce patient
        </a>
        <form action="{% url 'patients:delete_patient' patient.pk %}" method='POST'>
          {% csrf_token %}
          <!-- The Button that trigger the modal -->
          <button type="button" class="btn btn-danger btn-lg btn-cancel" data-toggle="modal" data-target="#deletePatientModal">
            <i class="fa fa-trash fa-right-margin"></i>
            Supprimer ce patient
          </button>
          <!-- Modal -->
          <div class="modal fade" id="deletePatientModal" tabindex="-1" role="dialog" aria-labelledby="deletePatientModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deletePatientModalLabel">Confirmer la supression du patient</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Votre relation avec ce patient va être supprimer definitivement. 
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                  <button type="submit" class="btn btn-danger">
                    <i class="fa fa-trash fa-right-margin"></i>
                    Confirmer
                  </button>
                </div>
              </div>
            </div>
          </div>
        </form>
    </div>

    </div>

  </div>
  {% endblock %}