echoTeleExpertise/echoTeleExpertise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('news/', views.news, name="news"),
    path('admin/', admin.site.urls),
    path('requests/', include('exams.url', namespace="exams")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('patients/', include('patients.urls', namespace="patients")),
    path('pages/', include('pages.urls', namespace="pages")),
    path('verify_email/<str:hash_code>/', views.activate_account, name="activate_account"),
    path('change_password/<str:hash_code>/', views.change_password, name="change_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

echoTeleExpertise/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('list_patients/', views.list_patients, name="list_patients"),
    path('telefiles/', views.telefiles, name="telefiles"),
    path('telefile/<int:request_id>', views.telefile, name="telefile"),
    path('telefile/share/<int:request_id>', views.share_request, name="share_request"),
    path('telefile/share_request/<int:request_id>', views.share_telefile, name="share_telefile"),
    path('telefile/send/<int:request_id>', views.send_rapport, name="send_rapport"),
    path('list_requests/', views.list_requests, name="list_requests"),
    path('list_doctors/', views.list_doctors, name="list_doctors"),
    path('doctor/<int:doctor_id>', views.doctor, name="doctor"),
    path('requests_history/', views.requests_history, name="requests_history"),
    path('opinions_history/', views.opinions_history, name="opinions_history")
]

echoTeleExpertise/templates/pages/partials/_sideNav.html
<div class="col-3">
    <div class="sidebar">
        <a {% if request.path == '/pages/list_patients/' %} class="active" {% endif %}
            href="{% url 'pages:list_patients' %}">
            <i class="fa fa-right-margin fa-procedures" aria-hidden="true"></i>
            <span class="text-sidebar">Listes des patients</span>
        </a>
        <a {% if request.path == '/pages/telefiles/' %} class="active" {% endif %} href="{% url 'pages:telefiles' %}">
            <i class="fa fa-right-margin fa-folder-open" aria-hidden="true"></i>
            <span class="text-sidebar">Télé-dossiers</span>
        </a>
        <a {% if request.path == '/pages/list_requests/' %} class="active" {% endif %}
            href="{% url 'pages:list_requests' %}">
            <i class="fa fa-right-margin fa-paper-plane"></i>
            <span class="text-sidebar">Demande d'avis d'expertise</span>
        </a>
        <a {% if request.path == '/pages/list_doctors/' %} class="active" {% endif %}
            href="{% url 'pages:list_doctors' %}">
            <i class="fa fa-right-margin fa-user-md"></i>
            <span class="text-sidebar">Listes des médecins</span>
        </a>
        <a {% if request.path == '/pages/requests_history/' %} class="active" {% endif %}
            href="{% url 'pages:requests_history' %}">
            <i class="fa fa-right-margin fa-comments"></i>
            <span class="text-sidebar">Historique des demandes</span>
        </a>
        <a {% if request.path == '/pages/opinions_history/' %} class="active" {% endif %}
            href="{% url 'pages:opinions_history' %}">
            <i class="fa fa-right-margin fa-reply-all"></i>
            <span class="text-sidebar">Historique des avis</span>
        </a>
        <a {% if request.path == '/dwv/' %} class="active" {% endif %}
            href="http://127.0.0.1:9000/">
            <i class="fa fa-right-margin fa-chalkboard"></i>
            <span class="text-sidebar">DICOM Visionnaire</span>
        </a>
    </div>
</div>