echoTeleExpertise/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('img_profile/', views.upload_profile_img, name="upload_profile_img"),
    path('forget_password/', views.forget_password, name="forget_password"),
    path('set_password/', views.set_password, name="set_password"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout, name="logout"),
    path('login/', views.login, name="login"),
]

echoTeleExpertise/echoTeleExpertise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('news/', views.news, name="news"),
    path('admin/', admin.site.urls),
    path('requests/', include('exams.url', namespace="exams")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('patients/', include('patients.urls', namespace="patients")),
    path('pages/', include('pages.urls', namespace="pages")),
    path('verify_email/<str:hash_code>/', views.activate_account, name="activate_account"),
    path('change_password/<str:hash_code>/', views.change_password, name="change_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

echoTeleExpertise/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('list_patients/', views.list_patients, name="list_patients"),
    path('telefiles/', views.telefiles, name="telefiles"),
    path('telefile/<int:request_id>', views.telefile, name="telefile"),
    path('telefile/share/<int:request_id>', views.share_request, name="share_request"),
    path('telefile/share_request/<int:request_id>', views.share_telefile, name="share_telefile"),
    path('telefile/send/<int:request_id>', views.send_rapport, name="send_rapport"),
    path('list_requests/', views.list_requests, name="list_requests"),
    path('list_doctors/', views.list_doctors, name="list_doctors"),
    path('doctor/<int:doctor_id>', views.doctor, name="doctor"),
    path('requests_history/', views.requests_history, name="requests_history"),
    path('opinions_history/', views.opinions_history, name="opinions_history")
]

echoTeleExpertise/templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

echoTeleExpertise/templates/partials/_mini_profile.html
{% load myconvertions %}

<div class="md-4">
    <ul class="nav-item dropdown">
        <span class="nav-link dropdown-toggle" style="color:white" href="#" id="navbarDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if user.is_staff %}
            <i class="fas fa-wrench fa-right-margin"></i>
            <span class="nav-item nav-profile-name">Admin {{ user | get_fullname }}</span>
            {% else %}
            <img class="align-self-center mr-3 rounded-circle nav-profile-img" src="{{ user.avatar.url }}"
                alt="profile image">
            <span class="nav-item nav-profile-name">{{ user | get_docname }}</span>
            {% endif %}
        </span>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">
                <i class="fas fa-user-edit fa-right-margin"></i> <span class="nav-item">Editer le profil</span>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="javascript:{
              document.getElementById('logout').submit()
            }">
                <i class="fas fa-power-off fa-right-margin"></i> <span class="nav-item">Se déconnecter</span>
            </a>
            <form id="logout" action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" />
            </form>
        </div>
    </ul>
</div>

echoTeleExpertise/templates/partials/_navbar.html
{% load static %}
{% load myconvertions %}

<nav class="navbar navbar-expand-lg sticky-top navbar-dark navbar-style">

  <!-- Brand name & image -->
  <a class="navbar-brand" href="{% url 'index' %}">
    <img src="{% static 'img/long_logo.png' %}" class="logo" width="280" height="47" alt="logo"/>
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <!-- Menu -->
    {% if user.is_authenticated %}
    <div class="row ml-auto">

      <!-- Mini Profile -->
      {% include 'partials/_mini_profile.html' %}

      <!-- Board Table -->
      {% if request.path == '/' or request.path == '/accounts/edit_profile/' %}
      <div class="md-4">
        <a class="btn btn-outline-primary btn-margin btn-bord-table" href="{% url 'pages:telefiles' %}">
          <i class="fas fa-columns fa-right-margin nav-board-table-icon"></i>
          <span class="nav-item nav-board-table">Tableau de bord</span>
        </a>
      </div>
      {% endif %}

      <!-- Notifications -->
      {% include 'partials/_notifications.html' %}

    </div>

  {% else %}

  <!-- Login & Register buttons -->
  <div class="ml-auto">
    <a class="btn btn-primary btn-margin btn-login-style" href="{% url 'accounts:login' %}">
      <i class="fas fa-sign-in-alt fa-right-margin"></i> <span class="nav-item">Connexion</span>
    </a>
    <a class="btn btn-outline-success btn-margin" href="{% url 'accounts:register' %}">
      <i class="fas fa-plus fa-right-margin"></i> <span class="nav-item">Inscription</span>
    </a>
  </div>
  {% endif %}

  </div>
</nav>

echoTeleExpertise/templates/partials/_notifications.html
{% load myconvertions %}
{% load humanize %}

{% if request.path != '/news/' %}
<div class="md-2 ml-auto">
  <ul class="dropdown" style="margin: 0.4em 0">
    <!-- Icon-->
    <span class="dropdown-toggle" style="color:#142850" href="#" id="navbarDropdown" role="button"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span>
        <i class="fas fa-bell icon-notification"></i>
        {% if notifications.len > 0 %}
        <span class="badge badge-danger nbr-notification">
          {{ notifications.len }}
        </span>
        {% endif %}
      </span>
    </span>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      {% if notifications.len > 0 %}

      {% for notif in notifications.summary %}
      <div class="media notification-media notification-small">
        <!-- News -->
        {% if notif.is_close == False %}
        {% if notif.is_incomplete == False %}
        {% if notif.expert_id == user %}
        <!-- The New telefiles-->

        <img class="align-self-center mr-3 rounded-circle notification-img" src="{{ notif.doctor_id.avatar.url }}"
          alt="profile image">
        <a class="notification-link" href="{% url 'pages:telefile' notif.pk %}">
          <div class="media-body">
            <div class="notification-infos">
              Nouvelle Demande de {{ notif.doctor_id | get_docname }}
            </div>
            <div>
              {% if notif.is_urgent %}
              <i class="fa fa-exclamation-triangle fa-right-margin" style="color:#cf0000; font-size: 0.7em"></i>
              <small>Urgent</small>
              {% endif %}
            </div>
            <small>{{ notif.notification_date | naturaltime }}</small>
          </div>
        </a>

        {% else %}
        <!-- The Experts Vues -->
        <img class="align-self-center mr-3 rounded-circle notification-img" src="{{ notif.expert_id.avatar.url }}"
          alt="profile image">
        <a class="notification-link" href="{% url 'exams:request_detail' notif.pk %}"></a>
          <div class="media-body">
            <div class="notification-infos">
              {{ notif.expert_id | get_docname }} a vu votre demande
            </div>
            <div>
              <i class="fa fa-search fa-right-margin" style="color: green; font-size: 0.7em"></i>
              <small>Vu</small>
            </div>
            <small>{{ notif.notification_date | naturaltime }}</small>
          </div>
        </a>
        {% endif %}

        {% else %}
        <!-- the new incomplete requests-->

        <img class="align-self-center mr-3 rounded-circle notification-img" src="{{ notif.expert_id.avatar.url }}"
          alt="profile image">
        <a class="notification-link" href="{% url 'exams:request_detail' notif.pk %}">
          <div class="media-body">
            <div class="notification-infos">
              {{ notif.expert_id | get_docname }} a besoin de plus d'informations.
            </div>
            <div>
              <i class="fa fa-redo fa-right-margin" style="color:#142850; font-size: 0.7em"></i>
              <small>Incomplet</small>
            </div>
            <small>{{ notif.notification_date | naturaltime }}</small>
          </div>
        </a>

        {% endif %}
        {% else %}
        <!-- the new solved requests -->

        <img class="align-self-center mr-3 rounded-circle notification-img" src="{{ notif.expert_id.avatar.url }}"
          alt="profile image">
        <a class="notification-link" href="{% url 'exams:request_solved_detail' notif.pk %}">
          <div class="media-body">
            <div class="notification-infos">
              {{ notif.expert_id | get_docname }} a envoyé son avis d'expertise.
            </div>
            <div>
              <i class="fa fa-check-circle fa-right-margin" style="color:green; font-size: 0.8em"></i>
              <small>Terminer</small>
            </div>
            <small>{{ notif.notification_date | naturaltime }}</small>
          </div>
        </a>

        {% endif %}
      </div>
      <hr />
      {% endfor %}

      <a class="dropdown-item" href="{% url 'news' %}" style="background-color: #eff5fb; text-align: center">
        <span class="nav-item">
          <i class="fa fa-plus fa-right-margin"></i>
          Afficher tous
        </span>
      </a>
    </div>
    {% else %}
    <a class="dropdown-item">
      <span class="nav-item">Pas de notifications</span>
    </a>
    {% endif %}
  </ul>
</div>
{% endif %}

echoTeleExpertise/templates/partials/_topbar.html
<section id="top-bar" class="p-3">
    <div class="container">
        <div class="row  social">
            <div class="col-md-4">
                <i class="fas fa-phone"></i> (+212)5 3255 5587
            </div>
            <div class="col-md-4">
                <i class="fas fa-envelope-open"></i> contact@ete.com
            </div>
            <div class="col-md-4">
                <div class="text-right social-icons">
                    <a href="https://twitter.com/explore">
                        <i class="fab fa-twitter"  style="color: #1DA1F2"></i>
                    </a>
                    <a href="https://www.facebook.com">
                        <i class="fab fa-facebook" style="color:#4267B2"></i>
                    </a>
                    <a href="https://www.linkedin.com">
                        <i class="fab fa-linkedin" style="color: #0E76A8"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
  </section>