echoTeleExpertise/echoTeleExpertise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('news/', views.news, name="news"),
    path('admin/', admin.site.urls),
    path('requests/', include('exams.url', namespace="exams")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('patients/', include('patients.urls', namespace="patients")),
    path('pages/', include('pages.urls', namespace="pages")),
    path('verify_email/<str:hash_code>/', views.activate_account, name="activate_account"),
    path('change_password/<str:hash_code>/', views.change_password, name="change_password"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

echoTeleExpertise/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('list_patients/', views.list_patients, name="list_patients"),
    path('telefiles/', views.telefiles, name="telefiles"),
    path('telefile/<int:request_id>', views.telefile, name="telefile"),
    path('telefile/share/<int:request_id>', views.share_request, name="share_request"),
    path('telefile/share_request/<int:request_id>', views.share_telefile, name="share_telefile"),
    path('telefile/send/<int:request_id>', views.send_rapport, name="send_rapport"),
    path('list_requests/', views.list_requests, name="list_requests"),
    path('list_doctors/', views.list_doctors, name="list_doctors"),
    path('doctor/<int:doctor_id>', views.doctor, name="doctor"),
    path('requests_history/', views.requests_history, name="requests_history"),
    path('opinions_history/', views.opinions_history, name="opinions_history")
]

echoTeleExpertise/patients/urls.py
from django.urls import path, include
from . import views

app_name = 'patients'

urlpatterns = [
    path('add/', views.add_patient, name="add_patient"),
    path('delete/<int:patient_id>/', views.delete_patient, name="delete_patient"),
    path('edit/<int:patient_id>/', views.edit_patient, name="edit_patient"),
    path('<int:patient_id>/', views.patient, name="patient")
]

echoTeleExpertise/patients/models.py
from django.db import models
from core.models import User
from datetime import datetime
from echoTeleExpertise.consts import GENDER_CHOICES

# Patients Model
class   Patient(models.Model):
    last_name = models.CharField('Nom', max_length=20)
    first_name = models.CharField('Prénom', max_length=30)
    cin = models.CharField('CIN', max_length=15)
    gender = models.CharField('Sexe', max_length=1, choices=GENDER_CHOICES)
    birthdate = models.DateField('Date de naissance')

    def     __str__(self):
        return (self.cin + ' | ' + self.last_name + ' ' + self.first_name)

# This Model is a relation many-to-many between Doctors & Patients
class   Relation(models.Model):
    patient_id = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor_id = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.CharField('Téléphone', max_length=10)
    join_date = models.DateTimeField('Date du premier contact', auto_now_add=True)

    def     __str__(self):
        return ('doctor ' + str(self.doctor_id) + ' | patient ' + str(self.patient_id))

echoTeleExpertise/templates/pages/list_patients.html
{% extends 'base.html' %}

{% block title %} List des patients {% endblock %}

{% block body %}
<div class="row" style="width:100vw">
  <!-- Side Nav -->
  {% include 'pages/partials/_sideNav.html' %}

  <div class="col-9" style="margin: 2em 0;">

    <!-- Alert -->
    {% include 'partials/_alerts.html' %}

    <!-- Search Area -->
    <form action="{% url 'pages:list_patients' %}">
    <div class="form-row">
      <!-- Name -->
      <div class="col-md-4 mb-3">
        <label class="sr-only">Nom et Prénom</label>
        <input type="text" name="search_name" class="form-control" placeholder="Nom ou Prénom"
          value="{{ values.search_name }}">
      </div>
      <!-- CIN -->
      <div class="col-md-2 mb-3">
        <label class="sr-only">C.I.N</label>
        <input type="text" name="search_cin" class="form-control" placeholder="C.I.N"
          value="{{ values.search_cin }}">
      </div>
      <!-- Gender -->
      <div class="col-md-3 mb-3">
        <label class="sr-only">Sexe</label>
        <select name="search_gender" class="form-control">
          <option selected="true" value="">Sexe</option>
          <option value="M"
            {% if values.search_gender == 'M' %}
              selected
            {% endif %}
          >
            Homme
          </option>
          <option value="F"
            {% if values.search_gender == 'F' %}
              selected
            {% endif %}
          >
            Femme
          </option>
        </select>
      </div>
      <!-- Start search button -->
      <div class="col-md-3 mb-3 search-btn">
        <button class="btn btn-info" type="submit">
          <i class="fa fa-right-margin fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  {% if relations %}

    <small class="small-info">
      <i class="fa fa-info-circle"></i>
      Appuyer sur le CIN pour voir les détails.
    </small>

    <table class="table table-striped" style="margin-top: 2em;">
      <thead>
        <tr>
          <th scope="col">C.I.N</th>
          <th scope="col">Nom du Patient</th>
        </tr>
      </thead>
      <tbody>
        {% for relation in relations %}
        <tr>
          <td>
            <a href="{% url 'patients:patient' relation.patient_id.pk %}" style="text-decoration: none;">
              {{ relation.patient_id.cin }}
            </a>
          </td>
          <td>{{ relation.patient_id.first_name }} {{ relation.patient_id.last_name }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <!-- Pagination -->
    {% if relations.has_other_pages %}
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <!-- Previous Pagination Button -->
        {% if relations.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ relations.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% endif %}
        <!-- all elements show -->
        {% for i in relations.paginator.page_range %}
        {% if relations.number == i %}
        <li class="page-item active">
          <a class="page-link" href="">{{ i }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- Next Pagination Button -->
        {% if relations.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ relations.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" aria-label="Next">
            <span aria-hidden="true">&raquo;</span> </a>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    {% else %}
    <div class="alert alert-info" role="alert">
      Vous n avez aucun patient enregister dans la plateforme!
    </div>
    {% endif %}
    <!-- Button -->
    <a href="{% url 'patients:add_patient' %}" class="btn btn-info btn-lg btn-block" style="margin-top: 2em">
      <i class="fa fa-plus fa-right-margin"></i>
      Ajouter un nouvaux patient
    </a>
  </div>
</div>
{% endblock %}

echoTeleExpertise/templates/pages/share_telefile.html
{% extends 'base.html' %}
{% load humanize %}
{% load myconvertions %}

{% block title %} Partager le télé-dossier {{ req.pk }} {% endblock %}

{% block body %}
<div class="row" style="width:100vw">
    <!-- Side Nav -->
    {% include 'pages/partials/_sideNav.html' %}

    <!-- Doctor Card -->
    <div class="col-9" style="margin: 2em 0;">

        <!-- Alert -->
        {% include 'partials/_alerts.html' %}

        <h3 class="file-header">
          Partager le télé-dossier
        </h3>

        <div class="card telefile-card">
            <div class="card-header telefile-card-pd0">
              <table class="table table-borderless telefile-table-brdless">
                <tbody>
                  <tr>
                    <td>Demandeur d'avis:</td>
                    <td>{{ req.doctor_id | get_docname }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="card-body telefile-card-pd0">
              <table class="table telefile-card-mrg0">
                <tbody>
                  <tr>
                    <th scope="row">Spécialité:</th>
                    <td>{{ req.doctor_id.speciality }}</td>
                  </tr>
                  <tr>
                    <th scope="row">Etablissement:</th>
                    <td>{{ req.doctor_id.institution }}</td>
                  </tr>
                  <tr>
                  <tr>
                    <th scope="row">Date de l'examen:</th>
                    <td>{{ req.exam_date }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <!-- Patient Card -->
          <div class="card telefile-card">
            <div class="card-header telefile-card-pd0">
              <table class="table table-borderless telefile-table-brdless">
                <tbody>
                  <tr>
                    <td>Patient:</td>
                    <td>{{ req.patient_id | get_fullname }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="card-body telefile-card-pd0">
              <table class="table telefile-card-mrg0">
                <tbody>
                  <tr>
                    <th scope="row">CIN:</th>
                    <td>{{ req.patient_id.cin }}</td>
                  </tr>
                  <tr>
                    <th scope="row">Sexe:</th>
                    <td>{{ req.patient_id.get_gender_display }}</td>
                  </tr>
                  <tr>
                    <th scope="row">Né(e) le:</th>
                    <td>{{ req.patient_id.birthdate }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <!-- Description Card -->
          <div class="card telefile-card">
            <div class="card-header">
              Description

              <!-- Urgent Badge -->
              {% if req.is_urgent %}
              <span class="badge badge-danger badge-urgent">
                <i class="fa fa-exclamation-triangle fa-right-margin"></i>
                Urgent
              </span>
              {% endif %}

            </div>
            <div class="card-body">
              <h5 style="margin-bottom: 1em;">
                {{ req.subject }}
              </h5>
              <blockquote class="blockquote mb-0">
                <p>{{ req.text_doctor }}</p>
                <footer class="blockquote-footer">
                  {{ req.create_date | naturaltime }}
                </footer>
              </blockquote>
            </div>
          </div>

          <!-- Document Card -->
          {% if documents %}
          <div class="card telefile-card">
            <div class="card-header">
              Documents Joints
            </div>   
            <div class="card-body telefile-card-pd0">
              <table class="table telefile-card-mrg0">
                <tbody>
                  {% for document in documents %}
                  <tr>
                    <th>
                      <a href="/media/{{ document.file}}" style="color:#142850; text-decoration:none">
                        <i class="fas fa-file-alt fa-right-margin"></i>
                        {{ document.name }}
                      </a>
                    </th>
                    <td>
                      <a href="/media/{{ document.file }}" download><i class="fas fa-download"></i></a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          {% endif %}

          <!-- Share the Request -->
          <div id="share-result">
            <hr style="margin: 4em" />
              <div class="card telefile-card">
                <div class="card-header">
                  Envoyé la demande aux Médecins:
                </div> 
                <div class="card-body telefile-card-pd0">
                  <div class="form-group" style="margin: 1em">
                    <!-- Search Area -->
                    <form action="{% url 'pages:share_telefile' req.pk %}">
                      <div class="form-row">
                        <!-- Speciality -->
                        <div class="col-md-5 mb-3">
                          <label class="sr-only">Spécialité</label>
                          <input type="text" name="search_speciality" class="form-control" placeholder="Spécialité"
                            value="{{ values.search_speciality }}">
                        </div>
                        <!-- City -->
                        <div class="col-md-4 mb-3">
                          <label class="sr-only">Ville</label>
                          <input type="text" name="search_city" class="form-control" placeholder="Ville"
                            value="{{ values.search_city }}">
                        </div>
                        <!-- Start search button -->
                        <div class="col-md-3 mb-3 search-btn">
                          <button class="btn btn-info" type="submit">
                            <i class="fa fa-right-margin fa-search"></i>
                          </button>
                        </div>
                      </div>
                    </form>
                    <hr/>
                    <form action="{% url 'pages:share_request' req.pk %}" method="POST" enctype='multipart/form-data'>
                      {% csrf_token %}
                    <!-- Select Doctor -->
                    {% if experts %}
                    <label class="sr-only">Medecins</label>
                    <select name="expert" class="form-control">
                      <option selected="true" value="">Les médecins</option>
                      {% for expert in experts %}
                        <option value="{{ expert.pk }}">
                          {{ expert | get_fullname }}
                        </option>
                      {% endfor %}
                    </select>
                    {% else %}
                    <div style="color:red; text-align:center">
                      Aucun Médecin avec cette spécification
                    </div>
                    {% endif %}
                    <!-- New Subject -->
                    <div class="form-group">
                      <div style="padding: 1em 0 0.5em 0.5em;">Mon Rapport:</div>
                      <div class="card-body telefile-card-pd0">
                        <textarea name="new_subject" class="form-control" id="exampleFormControlTextarea1" rows="1" placeholder="Objet"></textarea>
                      </div>
                    </div>
                    <!-- Additional Description -->
                    <div class="form-group">
                      <div class="card-body telefile-card-pd0">
                        <textarea name="text_additional" class="form-control" id="exampleFormControlTextarea1" rows="6" placeholder="Description supplémentaire"></textarea>
                      </div>
                    </div>
                    <!-- Files -->
                    <div class="form-group">
                      <div class="custom-file">
                        <input name="new_files" type="file" class="custom-file-input" id="customFileLangHTML" multiple>
                        <label class="custom-file-label" for="customFileLangHTML" data-browse="Fichiers">
                          Fichiers à joindre (facultatif)
                        </label>
                      </div>
                    </div>
                    <hr>
                    <!-- The request is urgent -->
                    <div class="form-group" style="text-align:center">
                      <div class="form-check">
                        <input type="checkbox" name="is_urgent" value="URGENT" id="defaultCheck1" class="form-check-input" style="width: 1em; height:1em;">
                        &nbsp;
                        <label class="form-check-label" for="defaultCheck1" style="color:red; font-weight: 600;">
                          Cette demande est Urgente !
                        </label>
                      </div>
                    </div>
                </div>
              </div>
            </div>
            <!-- Send-Cancel Buttons -->
            <div class="send-cancel">
              <!-- buttons -->
              <button type="button" class="btn btn-success btn-lg btn-send" data-toggle="modal" data-target="#shareRequestModal">
                <i class="fa fa-paper-plane fa-right-margin"></i>
                Envoyer la demande
              </button>
              <a href="{% url 'pages:telefile' req.pk %}" class="btn btn-warning btn-lg btn-cancel">
                Annuler
              </a>
              <!-- Modal -->
              <div class="modal fade" id="shareRequestModal" tabindex="-1" role="dialog" aria-labelledby="shareRequestModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="additionalInfosModalLabel">
                        Confirmer le partage de la demande
                      </h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      Cette demande sera partager avec l'expert et vous serais propriétaire de cette demandeur de l'avis d'expertise, mais le nom de l'origine demandeur sera afficher avec sa description, cette demande ne sera pas modifiable après l'envoi!
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                      <button type="submit" class="btn btn-success">
                        <i class="fa fa-paper-plane fa-right-margin"></i>
                        Envoyer
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </div>
          </form>


    </div>
</div>
{% endblock %}

echoTeleExpertise/templates/pages/telefile.html
{% extends 'base.html' %}
{% load myconvertions %}
{% load humanize %}

{% block title %} Télé-dossier {{ req.pk }} {% endblock %}

{% block body %}
<div class="row" style="width:100vw">
  <!-- Side Nav -->
  {% include 'pages/partials/_sideNav.html' %}

  <!-- Doctor Card -->
  <div class="col-9" style="margin: 2em 0;">

    <!-- Alert -->
    {% include 'partials/_alerts.html' %}

    <h3 class="file-header">
      Télé-dossier
    </h3>
    <br/>

    <div class="card telefile-card">
      <div class="card-header telefile-card-pd0">
        <table class="table table-borderless telefile-table-brdless">
          <tbody>
            <tr>
              <td>Demandeur d'avis:</td>
              <td>{{ req.doctor_id | get_docname }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="card-body telefile-card-pd0">
        <table class="table telefile-card-mrg0">
          <tbody>
            <tr>
              <th scope="row">Spécialité:</th>
              <td>{{ req.doctor_id.speciality }}</td>
            </tr>
            <tr>
              <th scope="row">Etablissement:</th>
              <td>{{ req.doctor_id.institution }}</td>
            </tr>
            <tr>
            <tr>
              <th scope="row">Date de l'examen:</th>
              <td>{{ req.exam_date }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Patient Card -->
    <div class="card telefile-card">
      <div class="card-header telefile-card-pd0">
        <table class="table table-borderless telefile-table-brdless">
          <tbody>
            <tr>
              <td>Patient:</td>
              <td>{{ req.patient_id | get_fullname }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="card-body telefile-card-pd0">
        <table class="table telefile-card-mrg0">
          <tbody>
            <tr>
              <th scope="row">CIN:</th>
              <td>{{ req.patient_id.cin }}</td>
            </tr>
            <tr>
              <th scope="row">Sexe:</th>
              <td>{{ req.patient_id.get_gender_display }}</td>
            </tr>
            <tr>
              <th scope="row">Né(e) le:</th>
              <td>{{ req.patient_id.birthdate }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Description Card -->
    <div class="card telefile-card">
      <div class="card-header">
        Description

        <!-- Urgent Badge -->
        {% if req.is_urgent %}
        <span class="badge badge-danger badge-urgent">
          <i class="fa fa-exclamation-triangle fa-right-margin"></i>
          Urgent
        </span>
        {% endif %}

      </div>
      <div class="card-body">
        <h5 style="margin-bottom: 1em;">
          {{ req.subject }}
        </h5>
        <hr/>
        <blockquote class="blockquote mb-0">
          <pre class="descriptions">{{ req.text_doctor }}</pre>
          <footer class="blockquote-footer">
            {{ req.create_date | naturaltime }}
          </footer>
        </blockquote>
      </div>
    </div>

    <!-- Document Card -->
    {% if documents %}
    <div class="card telefile-card">
      <div class="card-header">
        Documents Joints
      </div>
      <div class="card-body telefile-card-pd0">
        <table class="table telefile-card-mrg0">
          <tbody>
            {% for document in documents %}
            <tr>
              <th>
                <a href="/media/{{ document.file}}" style="color:#142850; text-decoration:none">
                  <i class="fas fa-file-alt fa-right-margin"></i>
                  {{ document.name }}
                </a>
              </th>
              <td>
                <a href="/media/{{ document.file }}" download><i class="fas fa-download"></i></a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    {% endif %}

    <!-- Buttons -->
    <div id="main-buttons">
      <button type="button" class="btn btn-primary btn-lg btn-block" onclick="display_req_infos();">
        <i class="fas fa-question fa-right-margin"></i>
        Demander des informations complémentaires
      </button>
      <a href="{% url 'pages:share_telefile' req.pk %}" class="btn btn-info btn-lg btn-block">
        <i class="fas fa-share fa-right-margin"></i>
        Demander une expertise complémentaire
      </a>
      <button type="button" class="btn btn-success btn-lg btn-block" onclick="display_send();">
        Donner l'avis d'expertise
      </button>
    </div>

    <!-- Demande complement infos -->
    <form action="{% url 'exams:mark_incomplete' req.pk %}" method='POST'>
      {% csrf_token %}
      <div id="additional_infos">
        <hr style="margin: 4em" />
        {% csrf_token %}
        <div class="card telefile-card">
          <div class="card-header">
            Commentaire envoyer avec la demande
          </div>
          <div class="card-body telefile-card-pd0">
            <textarea name="text_expert" class="form-control" id="exampleFormControlTextarea1" rows="6"
              placeholder="Je vois que cette demande nécessite plus informations car ... comme ..."></textarea>
          </div>
        </div>
        <!-- Send-Cancel Buttons -->
        <div class="send-cancel">
          <button type="button" class="btn btn-primary btn-lg btn-send" data-toggle="modal" data-target="#additionalInfosModal">
            <i class="fa fa-question fa-right-margin"></i>
            Envoyer la demande des informations complementaire
          </button>
          <a href="{% url 'pages:telefile' req.pk %}" class="btn btn-warning btn-lg btn-cancel">
            Annuler
          </a>
          <!-- Modal -->
          <div class="modal fade" id="additionalInfosModal" tabindex="-1" role="dialog" aria-labelledby="additionalInfosModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="additionalInfosModalLabel">
                    Confirmer l'envoi de la demande
                  </h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Vous ne pouvez pas modifier ou annuler la demande des informations complémentaire en cas d'envoi.
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                  <button type="submit" class="btn btn-primary">
                    Confirmer
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </form>

    <!-- Send Result -->
    <form action="{% url 'pages:send_rapport' req.pk %}" method="POST" enctype='multipart/form-data'>
      <div id="send-result">
        <hr style="margin: 4em" />
        {% csrf_token %}
        <div class="card telefile-card">
          <div class="card-header">
            Mon Rapport:
          </div>
          <div class="card-body telefile-card-pd0">
            <textarea name="text_expert" class="form-control" id="exampleFormControlTextarea1" rows="6"
              placeholder="Après l'analyse de cette demande je conclu que ..."></textarea>
          </div>
        </div>
        <!-- Files -->
        <div class="form-group">
          <div class="custom-file">
            <input name="files" type="file" class="custom-file-input" id="customFileLangHTML" multiple>
            <label class="custom-file-label" for="customFileLangHTML" data-browse="Fichiers">
              Fichiers à joindre (facultatif)
            </label>
          </div>
        </div>
        <!-- Send-Cancel Buttons -->
        <div class="send-cancel">
          <button type="button" class="btn btn-success btn-lg btn-send" data-toggle="modal" data-target="#sendResponseModal">
            <i class="fa fa-paper-plane fa-right-margin"></i>
            Envoyer le rapport
          </button>
          <a href="{% url 'pages:telefile' req.pk %}" class="btn btn-warning btn-lg btn-cancel">
            Annuler
          </a>
          <!-- Modal -->
          <div class="modal fade" id="sendResponseModal" tabindex="-1" role="dialog" aria-labelledby="sendResponseModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="sendResponseModalLabel">
                    Confirmer l'envoi du rapport
                  </h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Vous ne pouvez pas modifier le rapport apres l'envoi.
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                  <button type="submit" class="btn btn-success">
                    <i class="fa fa-paper-plane fa-right-margin"></i>
                    Envoyer
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </form>

  </div>
  {% endblock %}